export default {
	symbols: {
		player: '@',
		empty: ' ',
		wall: 'X',
		target: '.',
		item: '+',
		active: '&',
	},
	programer: {
		player: 'face',
		empty: 'code',
		wall: 'desktop_windows',
		target: 'bug_report',
		item: 'healing',
		active: 'save',
	},
	christmas: {
		player: 'person',
		empty: 'space_bar',
		wall: 'ac_unit',
		target: 'location_city',
		item: 'card_giftcard',
		active: 'mood',
	},
	postman: {
		player: 'face',
		empty: 'space_bar',
		wall: 'location_city',
		target: 'person',
		item: 'mail',
		active: 'drafts',
	},
	keys: {
		player: 'face',
		empty: 'space_bar',
		wall: 'location_city',
		target: 'lock',
		item: 'vpn_key',
		active: 'lock_open',
	},
	farm: {
		player: 'face',
		empty: 'space_bar',
		wall: 'nature',
		target: 'spa',
		item: 'opacity',
		active: 'local_florist',
	},
}